### PR TITLE
Fix typeerror exception when importing dynamic data of synchronous machines

### LINKED ISSUE #23: TypeError Exception when importing dynamic data of Synchronous Machines
The parameter inertia of the class RotatingMachineDynamics is initialized in the contructor as an integer ([see here](https://github.com/sogno-platform/cimpy/blob/b49972e3c4d5b2d313ec5fd3bcb6c5fcd718d586/cimpy/cgmes_v2_4_15/RotatingMachineDynamics.py#L31C36-L31C40)).

When importing dynamic data, cimimport is converting the values of the cim files using the default value of the cimpy classes. That means, that cimimport tries to read the parameter _inertia_ fro the CIM files as an integer and not as a float which traslante into an exception when reading dynamic data of cim topologies ([see here](https://github.com/sogno-platform/cimpy/blob/817aeb2959b0d1644473013beccaed1709fc02c0/cimpy/cimimport.py#L268C44-L268C45))

The same bahaviour can be observed in the class [SynchronousMachineTimeConstantReactance](https://github.com/sogno-platform/cimpy/blob/b49972e3c4d5b2d313ec5fd3bcb6c5fcd718d586/cimpy/cgmes_v2_4_15/SynchronousMachineTimeConstantReactance.py#L47). The parameters _tpdo_, _tppdo_, _tpqo_, _tppqo_, _tc_ should be initialized as floats in the contructor of the class.

### PR DESCRIPTION
**Pull request by martinmoraga**
Issue #23

### CODE REVIEW

**Comment by m-mirz** [comment]
@martinmoraga could you please add the dco sign off? Then this can be merged.

**Comment by stv0g** [comment]
Has this been fixed in CIMgen? Fixing it just here wont help anybody in the long run as the changes will get lost when the code gets regenerated.

**Comment by m-mirz** [comment]
> Has this been fixed in CIMgen? Fixing it just here wont help anybody in the long run as the changes will get lost when the code gets regenerated.

I agree. My intention was to create an issue in cimgen when merging this so that we don’t forget this issue.

**Comment by martinmoraga** [comment]
> @martinmoraga could you please add the dco sign off? Then this can be merged.

@m-mirz Done!

But the pipeline fails now with the error: 

`Branch "23-typeerror-exception-when-importing-dynamic-data-of-synchronous-machines" is not allowed to deploy to github-pages due to environment protection rules.`

**Comment by stv0g** [comment]
> But the pipeline fails now with the error

Okay, thats my fault. Sorry I will have a look

**Comment by m-mirz** [comment]
This is covered in #39 and also fixed in cimgen thanks to @tom-hg57

**Pull request closed without merging**
