### PR TITLE
Fix Issue20

### PR DESCRIPTION
**Pull request by schmocker**
* Fix issue #20 
* Add .gitignore file

### CODE REVIEW

**Comment by schmocker** [comment]
@dinkelbachjan feel free to review and close this pr

**Comment by stv0g** [comment]
Thanks @schmocker :) However, I think we should remove the changes to the gitignore file in the PR as they are unrelated to the PR and actually covering to much files which are not created by the repo itself.

**Comment by schmocker** [comment]
> Thanks @schmocker :) However, I think we should remove the changes to the gitignore file in the PR as they are unrelated to the PR and actually covering to much files which are not created by the repo itself.

@stv0g sure thing - but still it's a nice thing to have a gitignore file in the repo 😉 I dropped the corresponding commit from this PR

**Comment by stv0g** [comment]
Thanks a lot @schmocker for the quick fix :)

**Pull request merged**
